services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    command: python -m src.bot
    depends_on:
      - db

  web:
    build: .
    restart: unless-stopped
    env_file: .env
    command: >
      uvicorn src.webapp.main:app
        --host 0.0.0.0
        --port 8000
        --proxy-headers
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:
