"""Make fio, specialization and email nullable

Revision ID: 300400afdcf3
Revises: 0001_initial_models
Create Date: 2025-07-18 19:45:57.588690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300400afdcf3'
down_revision: Union[str, Sequence[str], None] = '0001_initial_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fio',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'specialization',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'specialization',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'fio',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
